<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>AdminHome</title>
<meta name="description" content="">                                                                                                                                                                                                                                                  
<meta name="viewport" content="width=device-width, initial-scale=1">                                                                                                                                                                                                                   
<meta name="robots" content="all,follow">                                                                                                                                                                                                                                              
<!-- Bootstrap CSS-->                                                                                                                                                                                                                                                                      
<link rel="stylesheet" href="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/bootstrap/css/bootstrap.min.css">                                                                                                                                                 
<!-- Font Awesome CSS-->                                                                                                                                                                                                                                                                   
<link rel="stylesheet" href="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/font-awesome/css/font-awesome.min.css">                                                                                                                                           
<!-- Fontastic Custom icon font-->                                                                                                                                                                                                                                                         
<link rel="stylesheet" href="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/css/fontastic.css">                                                                                                                                                                      
<!-- Google fonts - Roboto -->                                                                                                                                                                                                                                                             
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">                                                                                                                                                                                          
<!-- jQuery Circle-->                                                                                                                                                                                                                                                                      
<link rel="stylesheet" href="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/css/grasp_mobile_progress_circle-1.0.0.min.css">                                                                                                                                         
<!-- Custom Scrollbar-->                                                                                                                                                                                                                                                                   
<link rel="stylesheet" href="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css">                                                                                                                      
<!-- theme stylesheet-->                                                                                                                                                                                                                                                                   
<link rel="stylesheet" href="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/css/style.default.premium.css" id="theme-stylesheet">                                                                                                                                  
<!-- Custom stylesheet - for your changes-->                                                                                                                                                                                                                                               
<link rel="stylesheet" href="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/css/custom.css">                                                                                                                                                                         
<!-- Favicon-->                                                                                                                                                                                                                                                                            
<link rel="shortcut icon" href="https://d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/img/favicon.ico">                                                                                                                                                                          
<!-- Tweaks for older IEs--><!--[if lt IE 9]>                                                                                                                                                                                                                                              
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>                                                                                                                                                                                                      
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->                                                                                                                                                                                              
<script type="text/javascript">                                                                                                                                                                                                                                                         
function sizeFrame(frameId) {                                                                                                                                                                                                                                                         
var F = document.getElementById(frameId);                                                                                                                                                                                                                                         
if (F.contentDocument) {                                                                                                                                                                                                                                                          
F.height = "";                                                                                                                                                                                                                                                              
F.height = F.contentDocument.documentElement.scrollHeight + 0; //FF 3.0.11, Opera 9.63, and Chrome                                                                                                                                                                            
} else {                                                                                                                                                                                                                                                                          
F.height = F.contentWindow.document.body.scrollHeight + 0; //IE6, IE7 and Chrome                                                                                                                                                                                              
}                                                                                                                                                                                                                                                                                 
}                                                                                                                                                                                                                                                                                     
// window.onload=sizeFrame;                                                                                                                                                                                                                                                           
</script>                                                                                                                                                       
</head>
<body>
<center>
<%
try
{
session=request.getSession(false);//used to create object for get session values.
String sid = session.getValue("suid").toString();// get value
String ltime = session.getValue("stime").toString();
%>

<nav class="side-navbar">                                                                                                                                                                                                                                                                
<div class="side-navbar-wrapper">                                                                                                                                                                                                                                                      
<!-- Sidebar Header    -->                                                                                                                                                                                                                                                             
<div class="sidenav-header d-flex align-items-center justify-content-center">                                                                                                                                                                                                        
<!-- User Info-->                                                                                                                                                                                                                                                                    
<div class="sidenav-header-inner text-center"><img src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/img/user.png" alt="person" class="img-fluid rounded-circle">                                                                                        
<h2 class="h5">Login-ID: <%=sid %></h2><span>Login Time: <%=ltime %></span>                                                                                                                                                 
</div>                                                                                                                                                                                                                                                                               
<!-- Small Brand information, appears on minimized sidebar-->                                                                                                                                                                                                                        
<div class="sidenav-header-logo"><a  class="brand-small text-center"> <strong>S</strong><strong class="text-primary">N</strong></a></div>                                                                                                                                      
</div>                                                                                                                                                                                                                                                                                 
<!-- Sidebar Navigation Menus-->                                                                                                                                                                                                                                                       
<div class="main-menu">                                                                                                                                                                                                                                                              
<!--<h5 class="sidenav-heading">Main</h5>-->                                                                                                                                                                                                                                       
<ul id="side-main-menu" class="side-menu list-unstyled">                                                                                                                                                                                                                         
<li><a href="CourseInterface.jsp" target="aa"><i class="icon-form"></i>Course Reg</a></li>
<li><a href="BranchInterface.jsp" target="aa"><i class="icon-form"></i>Branch Reg</a></li>
<li><a href="SubjectInterface.jsp" target="aa"><i class="icon-form"></i>Subject Reg</a></li>
<li><a href="UserDisplay.jsp" target="aa"><i class="icon-form"></i>Show Users</a></li>
<li><a href="AdminLogout.jsp"><i class="icon-form"></i>Logout</a></li>                                                                                                                                                                               
</ul>                                                                                                                                                                                                                                                                                
</div>                                                                                                                                                                                                                                                                                 

</div>                                                                                                                                                                                                                                                                                   
</nav>                                                                                                                                                                                                                                                                                     
<div class="page">                                                                                                                                                                                                                                                                       
<!-- navbar-->                                                                                                                                                                                                                                                                           
<header class="header">                                                                                                                                                                                                                                                                
<nav class="navbar">                                                                                                                                                                                                                                                                 
<div class="container-fluid">                                                                                                                                                                                                                                                      
<div class="navbar-holder d-flex align-items-center justify-content-between">                                                                                                                                                                                                    
<div class="navbar-header"><a id="toggle-btn" href="#" class="menu-btn"><i class="icon-bars"> </i></a><a href="index-2.html" class="navbar-brand">                                                                                                                 
<!--<div class="brand-text d-none d-md-inline-block"><span>Bootstrap </span><strong class="text-primary">Dashboard</strong></div>--></a></div>                                                                                                                           
<ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">                                                                                                                                                                                                   
<!-- <li class="nav-item"><a href="adminlogin.jsp" class="nav-link logout">Logout<i class="fa fa-sign-out"></i></a></li> -->                                                                                                                                   
</ul>                                                                                                                                                                                                                                                                            
</div>                                                                                                                                                                                                                                                                             
</div>                                                                                                                                                                                                                                                                               
</nav>                                                                                                                                                                                                                                                                                 
</header>                                                                                                                                                                                                                                                                                
<section class="charts">                                                                                                                                                                                                                                                               
<div class="container-fluid">                                                                                                                                                                                                                                                        
<!-- Page Header-->                                                                                                                                                                                                                                                                  

<h1 class="h3 display">           </h1>                                                                                                                                                                                                                                          

<div class="row">                                                                                                                                                                                                                                                                  
<div class="col-lg-12">                                                                                                                                                                                                                                                          
<div class="card radar-chart-example">                                                                                                                                                                                                                                         
<!--<div class="card-header d-flex align-items-center">                                                                                                                                                                                                                      
<h2 class="h5 display">Radar Chart Example</h2>                                                                                                                                                                                                                            
</div>-->                                                                                                                                                                                                                                                                      
<div class="card-body">                                                                                                                                                                                                                                                      
<iframe width="100%" src="UserDisplay.jsp" style="border-left:0px #f1b458 solid;box-shadow: 5px 5px 20px #888888;border-top:height:auto;border-radius: 1px;" id="myFrame" name="aa" frameborder="0" onload="sizeFrame('myFrame')"></iframe>
</div>                                                                                                                                                                                                                                                                         
</div>                                                                                                                                                                                                                                                                           
</div>                                                                                                                                                                                                                                                                             
</div>                                                                                                                                                                                                                                                                               
</div>                                                                                                                                                                                                                                                                                 
</section>                                                                                                                                                                                                                                                                               
<footer class="main-footer">                                                                                                                                                                                                                                                           
<div class="container-fluid">                                                                                                                                                                                                                                                        
<div class="row">                                                                                                                                                                                                                                                                  
<!--<div class="col-sm-6">                                                                                                                                                                                                                                                       
<p>Your company &copy; 2017-2019</p>                                                                                                                                                                                                                                             
</div>-->                                                                                                                                                                                                                                                                          
<div class="col-sm-6 text-right">                                                                                                                                                                                                                                                
<p>Designed By: </p>                                                                                                                                                                                                                                                             
</div>                                                                                                                                                                                                                                                                             
</div>                                                                                                                                                                                                                                                                               
</div>                                                                                                                                                                                                                                                                                 
</footer>                                                                                                                                                                                                                                                                                
</div>                                                                                                                                                                                                                                                                                     
<!-- Javascript files-->                                                                                                                                                                                                                                                                   
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/jquery/jquery.min.js"></script>                                                                                                                                                                     
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/popper.js/umd/popper.min.js"> </script>                                                                                                                                                             
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/bootstrap/js/bootstrap.min.js"></script>                                                                                                                                                            
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/js/grasp_mobile_progress_circle-1.0.0.min.js"></script>                                                                                                                                                    
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/jquery.cookie/jquery.cookie.js"> </script>                                                                                                                                                          
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/chart.js/Chart.min.js"></script>                                                                                                                                                                    
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/jquery-validation/jquery.validate.min.js"></script>                                                                                                                                                 
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>                                                                                                                     
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/js/charts-home.js"></script>                                                                                                                                                                               
<!-- Notifications-->                                                                                                                                                                                                                                                                      
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/messenger-hubspot/build/js/mess1enger.min.js">   </script>                                                                                                                                          
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/vendor/messenger-hubspot/build/js/messenger-theme-flat.js">       </script>                                                                                                                                
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/js/home-premium.js"> </script>                                                                                                                                                                             
<!-- Main File-->                                                                                                                                                                                                                                                                          
<script src="adminhome/d19m59y37dris4.cloudfront.net/dashboard-premium/1-3/js/front.js"></script>                                                            

<%-- <table border="1">
<caption>Admin Home Page</caption>
<tr><td>Welcome: <%=sid %></td><td>Login Time: <%=ltime %></td></tr>
<tr><td><a href="CourseInterface.jsp" target="aa">Course Reg</a><br>
<a href="BranchInterface.jsp" target="aa">Branch Reg</a><br>
<a href="SubjectInterface.jsp" target="aa">Subject Reg</a><br>
<a href="UserDisplay.jsp" target="aa">Show Users</a><br>
<a href="AdminLogout.jsp">Logout</a><br>
</td><td><iframe name="aa" height="500" width="800" frameborder="0"></iframe></td></tr>
<tr><td>Footer</td><td>Footer</td></tr>
</table> --%>
<%
}
catch(Exception ex)
{
response.sendRedirect("AdminLogin.jsp");	
}
%>
</center>
</body>
</html>